# Student grade data set

In [1]:
import pandas as pd
import numpy as np

student_dataset = pd.read_csv('./StudentsPerformance.csv')

In [2]:
student_dataset

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [5]:
student_dataset.shape

(1000, 8)

In [6]:
type(student_dataset)

pandas.core.frame.DataFrame

In [7]:
type(student_dataset.columns)

pandas.core.indexes.base.Index

In [8]:
student_dataset.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [3]:
import numpy as np
student_dataset_np = np.array(student_dataset)

In [10]:
student_dataset.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [11]:
mean_math_score = student_dataset['math score'].mean()

In [12]:
# math score mean of student dataset
mean_math_score

66.089

In [13]:
writing_score_mean = student_dataset['writing score'].mean()

In [14]:
# writing score mean of student dataset
writing_score_mean

68.054

In [15]:
reading_score_mean = student_dataset['reading score'].mean()

In [16]:
# reading score mean of student dataset
reading_score_mean

69.169

In [17]:
math_median_score = student_dataset['math score'].median()

In [18]:
# math median score of student dataset
math_median_score

66.0

In [19]:
writing_median_score = student_dataset['writing score'].median()

In [20]:
# writing median score of student dataset
writing_median_score

69.0

In [21]:
reading_median_score = student_dataset['reading score'].median()

In [22]:
# reading median score of student dataset
reading_median_score

70.0

In [23]:
math_mode_score = student_dataset['math score'].mode()

In [24]:
math_mode_score

0    65
Name: math score, dtype: int64

In [25]:
writing_mode_score =  student_dataset['writing score'].mode()
writing_mode_score

0    74
Name: writing score, dtype: int64

In [26]:
readin_mode_score = student_dataset['reading score'].mode()
readin_mode_score

0    72
Name: reading score, dtype: int64

In [27]:
min_score_values = student_dataset.min()
min_score_values

gender                                     female
race/ethnicity                            group A
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                      0
reading score                                  17
writing score                                  10
dtype: object

In [31]:
max_score_values = student_dataset.max()
max_score_values

gender                                     male
race/ethnicity                          group E
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                  100
reading score                               100
writing score                               100
dtype: object

In [4]:
range_math_score_value = student_dataset['math score'].max() -  student_dataset['math score'].min()
range_score_values

NameError: name 'range_score_values' is not defined

In [32]:
std_math_score = student_dataset['math score'].std()
std_math_score

15.163080096009468

In [33]:
std_writing_score = student_dataset['writing score'].std()
std_writing_score

15.195657010869642

In [34]:
std_reading_score = student_dataset['reading score'].std()
std_reading_score

14.60019193725222

In [35]:
math_score_quantile =student_dataset['math score'].quantile([0.25,0.50,0.75])
math_score_quantile

0.25    57.0
0.50    66.0
0.75    77.0
Name: math score, dtype: float64

In [36]:
writing_score_quantile =student_dataset['writing score'].quantile([0.25,0.50,0.75])
writing_score_quantile

0.25    57.75
0.50    69.00
0.75    79.00
Name: writing score, dtype: float64

In [37]:
reading_score_quantile =student_dataset['reading score'].quantile([0.25,0.50,0.75])
reading_score_quantile

0.25    59.0
0.50    70.0
0.75    79.0
Name: reading score, dtype: float64

In [38]:
student_dataset['math score'].unique()

array([ 72,  69,  90,  47,  76,  71,  88,  40,  64,  38,  58,  65,  78,
        50,  18,  46,  54,  66,  44,  74,  73,  67,  70,  62,  63,  56,
        97,  81,  75,  57,  55,  53,  59,  82,  77,  33,  52,   0,  79,
        39,  45,  60,  61,  41,  49,  30,  80,  42,  27,  43,  68,  85,
        98,  87,  51,  99,  84,  91,  83,  89,  22, 100,  96,  94,  48,
        35,  34,  86,  92,  37,  28,  24,  26,  95,  36,  29,  32,  93,
        19,  23,   8], dtype=int64)

In [39]:
student_dataset['writing score'].unique()

array([ 74,  88,  93,  44,  75,  78,  92,  39,  67,  50,  52,  43,  73,
        70,  58,  86,  28,  46,  61,  63,  53,  80,  72,  55,  65,  38,
        82,  79,  83,  59,  57,  54,  68,  66,  62,  76,  48,  42,  87,
        49,  10,  34,  71,  37,  56,  41,  22,  81,  45,  36,  89,  47,
        90, 100,  64,  98,  51,  40,  84,  69,  33,  60,  85,  91,  77,
        27,  94,  95,  19,  35,  32,  96,  97,  99,  15,  30,  23],
      dtype=int64)

In [40]:
student_dataset['reading score'].unique()

array([ 72,  90,  95,  57,  78,  83,  43,  64,  60,  54,  52,  81,  53,
        75,  89,  32,  42,  58,  69,  73,  71,  74,  70,  65,  87,  56,
        61,  84,  55,  44,  41,  85,  59,  17,  39,  80,  37,  63,  51,
        49,  26,  68,  45,  47,  86,  34,  79,  66,  67,  91, 100,  76,
        77,  82,  92,  93,  62,  88,  50,  28,  48,  46,  23,  38,  94,
        97,  99,  31,  96,  24,  29,  40], dtype=int64)

# handling missing values

In [41]:
student_dataset.isnull().sum().sum()

gender  race/ethnicity  parental level of education  lunch  \
0     False           False                        False  False   
1     False           False                        False  False   
2     False           False                        False  False   
3     False           False                        False  False   
4     False           False                        False  False   
..      ...             ...                          ...    ...   
995   False           False                        False  False   
996   False           False                        False  False   
997   False           False                        False  False   
998   False           False                        False  False   
999   False           False                        False  False   

     test preparation course  math score  reading score  writing score  
0                      False       False          False          False  
1                      False       False          False          False  
2                      False       False          False          False  
3                      False       False          False          False  
4                      False       False          False          False  
..                       ...         ...            ...            ...  
995                    False       False          False          False  
996                    False       False          False          False  
997                    False       False          False          False  
998                    False       False          False          False  
999                    False       False          False          False  

[1000 rows x 8 columns]

In [42]:
student_dataset

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [56]:
# dataset_fill = student_dataset.fillna(value = 5)
# dataset_fill
# student_dataset.isnull().sum().sum()
# student_dataset.isnull()
student_dataset['test preparation course'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: test preparation course
Non-Null Count  Dtype 
--------------  ----- 
1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB


In [44]:
total_math_score  = student_dataset['math score'].sum()
len_student_subject_math = len(student_dataset['math score'])
total_math_score/len_student_subject_math

66.089

In [45]:
highest_score_male =student_dataset['reading score'][student_dataset['gender']== 'male'].idxmax()
result = student_dataset.loc[highest_score_male]
result

gender                                       male
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                    100
reading score                                 100
writing score                                  93
Name: 149, dtype: object

In [46]:
student_percentage = student_dataset['race/ethnicity'][student_dataset['test preparation course'] == "completed"]
student_percentage

1      group C
6      group B
8      group D
13     group A
18     group C
        ...   
990    group E
991    group B
995    group E
997    group C
998    group D
Name: race/ethnicity, Length: 358, dtype: object

In [47]:
parental_level = student_dataset['parental level of education'][student_dataset['writing score']]
parental_level

74      some high school
88          some college
93    associate's degree
44    associate's degree
75    associate's degree
             ...        
95    associate's degree
55           high school
65      some high school
77     bachelor's degree
86          some college
Name: parental level of education, Length: 1000, dtype: object

In [48]:
highest_math_score = student_dataset['math score'].max()
highest_writing_score = student_dataset['writing score'].max()
highest_reading_score = student_dataset['reading score'].max()

student_highest_score = highest_math_score + highest_writing_score + highest_reading_score
student_highest_score

300

In [49]:
students_highest_per = student_dataset['writing score'] >= 90
students_highest_per

0      False
1      False
2       True
3      False
4      False
       ...  
995     True
996    False
997    False
998    False
999    False
Name: writing score, Length: 1000, dtype: bool

In [50]:
race_ethnicity_group = student_dataset['race/ethnicity'][student_dataset ['reading score'].max()]
race_ethnicity_group

'group B'

In [51]:
female_highest_score = [student_dataset['gender'] == 'female'] and [student_dataset['reading score'].max()] and [student_dataset['writing score'].max()] and [student_dataset['math score'].max()]
female_highest_score

[100]

In [52]:
students_score_50 = [student_dataset['math score'] <= 50 ] and [student_dataset['writing score'] <= 50 ] and [student_dataset['reading score'] <= 50 ]
students_score_50

[0      False
 1      False
 2      False
 3      False
 4      False
        ...  
 995    False
 996    False
 997    False
 998    False
 999    False
 Name: reading score, Length: 1000, dtype: bool]